package constant;

public enum ErrorCode {

    INVALID_INPUT,
    INVALID_STATUS,
    INVALID_COMMAND,
    INVALID_POSITION,
    INVALID_MOVEMENT_RULE,
    PIECE_EXIST_IN_ROUTE,
    PIECE_DOES_NOT_EXIST_POSITION,
    INVALID_CAMP_PIECE,
    NO_MESSAGE;

}
