export const PIECES = {
  K: `<img src= "/image/K.png"/>`,
  Q: `<img src= "/image/Q.png"/>`,
  B: `<img src= "/image/B.png"/>`,
  N: `<img src= "/image/N.png"/>`,
  R: `<img src= "/image/R.png"/>`,
  P: `<img src= "/image/P.png"/>`,
  k: `<img src= "/image/w_K.png"/>`,
  q: `<img src= "/image/w_Q.png"/>`,
  b: `<img src= "/image/w_B.png"/>`,
  n: `<img src= "/image/w_N.png"/>`,
  r: `<img src= "/image/w_R.png"/>`,
  p: `<img src= "/image/w_P.png"/>`,
  '.': `<img/>`,
}