package chess.domain;

import static chess.domain.position.FileCoordinate.A;
import static chess.domain.position.FileCoordinate.B;
import static chess.domain.position.FileCoordinate.C;
import static chess.domain.position.FileCoordinate.D;
import static chess.domain.position.FileCoordinate.E;
import static chess.domain.position.FileCoordinate.F;
import static chess.domain.position.FileCoordinate.G;
import static chess.domain.position.FileCoordinate.H;
import static chess.domain.position.RankCoordinate.EIGHT;
import static chess.domain.position.RankCoordinate.FIVE;
import static chess.domain.position.RankCoordinate.FOUR;
import static chess.domain.position.RankCoordinate.ONE;
import static chess.domain.position.RankCoordinate.SEVEN;
import static chess.domain.position.RankCoordinate.SIX;
import static chess.domain.position.RankCoordinate.THREE;
import static chess.domain.position.RankCoordinate.TWO;

import chess.domain.position.Position;

public class PositionFixture {
    public static final Position A_1 = new Position(A, ONE);
    public static final Position A_2 = new Position(A, TWO);
    public static final Position A_3 = new Position(A, THREE);
    public static final Position A_4 = new Position(A, FOUR);
    public static final Position A_5 = new Position(A, FIVE);
    public static final Position A_6 = new Position(A, SIX);
    public static final Position A_7 = new Position(A, SEVEN);
    public static final Position A_8 = new Position(A, EIGHT);
    public static final Position B_1 = new Position(B, ONE);
    public static final Position B_2 = new Position(B, TWO);
    public static final Position B_3 = new Position(B, THREE);
    public static final Position B_4 = new Position(B, FOUR);
    public static final Position B_5 = new Position(B, FIVE);
    public static final Position B_6 = new Position(B, SIX);
    public static final Position B_7 = new Position(B, SEVEN);
    public static final Position B_8 = new Position(B, EIGHT);
    public static final Position C_1 = new Position(C, ONE);
    public static final Position C_2 = new Position(C, TWO);
    public static final Position C_3 = new Position(C, THREE);
    public static final Position C_4 = new Position(C, FOUR);
    public static final Position C_5 = new Position(C, FIVE);
    public static final Position C_6 = new Position(C, SIX);
    public static final Position C_7 = new Position(C, SEVEN);
    public static final Position C_8 = new Position(C, EIGHT);
    public static final Position D_1 = new Position(D, ONE);
    public static final Position D_2 = new Position(D, TWO);
    public static final Position D_3 = new Position(D, THREE);
    public static final Position D_4 = new Position(D, FOUR);
    public static final Position D_5 = new Position(D, FIVE);
    public static final Position D_6 = new Position(D, SIX);
    public static final Position D_7 = new Position(D, SEVEN);
    public static final Position D_8 = new Position(D, EIGHT);
    public static final Position E_1 = new Position(E, ONE);
    public static final Position E_2 = new Position(E, TWO);
    public static final Position E_3 = new Position(E, THREE);
    public static final Position E_4 = new Position(E, FOUR);
    public static final Position E_5 = new Position(E, FIVE);
    public static final Position E_6 = new Position(E, SIX);
    public static final Position E_7 = new Position(E, SEVEN);
    public static final Position E_8 = new Position(E, EIGHT);
    public static final Position F_1 = new Position(F, ONE);
    public static final Position F_2 = new Position(F, TWO);
    public static final Position F_3 = new Position(F, THREE);
    public static final Position F_4 = new Position(F, FOUR);
    public static final Position F_5 = new Position(F, FIVE);
    public static final Position F_6 = new Position(F, SIX);
    public static final Position F_7 = new Position(F, SEVEN);
    public static final Position F_8 = new Position(F, EIGHT);
    public static final Position G_1 = new Position(G, ONE);
    public static final Position G_2 = new Position(G, TWO);
    public static final Position G_3 = new Position(G, THREE);
    public static final Position G_4 = new Position(G, FOUR);
    public static final Position G_5 = new Position(G, FIVE);
    public static final Position G_6 = new Position(G, SIX);
    public static final Position G_7 = new Position(G, SEVEN);
    public static final Position G_8 = new Position(G, EIGHT);
    public static final Position H_1 = new Position(H, ONE);
    public static final Position H_2 = new Position(H, TWO);
    public static final Position H_3 = new Position(H, THREE);
    public static final Position H_4 = new Position(H, FOUR);
    public static final Position H_5 = new Position(H, FIVE);
    public static final Position H_6 = new Position(H, SIX);
    public static final Position H_7 = new Position(H, SEVEN);
    public static final Position H_8 = new Position(H, EIGHT);
}
