package chess.model.exception;

public enum ChessExceptionType {

    COMMAND_NOT_FOUND,
    FILE_NOT_FOUND,
    RANK_NOT_FOUND,
    MOVEMENT_NOT_FOUND,
    GAME_ID_ILLEGAL_TYPE,
    REQUEST_NOT_CONTAIN_ID,
    REQUEST_NOT_CONTAIN_POSITION,
    DATABASE_CAN_NOT_CONNECT,
    QUERY_FAIL,
    END_CANT_EXECUTE,
    STARTED_CANT_EXECUTE,
    NOT_STARTED_CANT_EXECUTE,
    FROM_IS_EMPTY,
    IS_NOT_PIECE_TURN,
    CANT_MOVE_FROM_TO,
    CANT_MOVE_TO_SAME_COLOR,
    OBSTACLE_EXIST,
    EMPTY_CANT_EXECUTE;
}
