CREATE TABLE `command` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `origin` VARCHAR(10) NOT NULL,
  `target` VARCHAR(10) NOT NULL,
  `round` BIGINT UNSIGNED NOT NULL,
  `room_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE room (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  status TINYINT(1) NOT NULL DEFAULT 0,
  winner VARCHAR (30),
  PRIMARY KEY(id));



