CREATE SCHEMA IF NOT EXISTS `chess` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `chess` ;

CREATE TABLE game (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL UNIQUE,
    turn VARCHAR(10) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE chess_piece (
	id INT NOT NULL AUTO_INCREMENT,
    x INT NOT NULL,
    y INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    gid INT NOT NULL,
    color VARCHAR(10) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (gid) REFERENCES game (id) ON DELETE CASCADE
);


