CREATE TABLE chess (
    rank1 VARCHAR(10) NOT NULL,
    rank2 VARCHAR(10) NOT NULL,
    rank3 VARCHAR(10) NOT NULL,
    rank4 VARCHAR(10) NOT NULL,
    rank5 VARCHAR(10) NOT NULL,
    rank6 VARCHAR(10) NOT NULL,
    rank7 VARCHAR(10) NOT NULL,
    rank8 VARCHAR(10) NOT NULL,
    turn VARCHAR(10) NOT NULL
);