package chess;

public enum Movement {
    //@formatter:off
    // Default movements
    UP(0, 1),
    DOWN(0, -1),
    LEFT(-1, 0),
    RIGHT(1, 0),
    LEFT_UP(LEFT.x, UP.y),
    RIGHT_UP(RIGHT.x, UP.y),
    LEFT_DOWN(LEFT.x, DOWN.y),
    RIGHT_DOWN(RIGHT.x, DOWN.y),
    // Custom movements
    UP_UP(0, UP.y * 2),
    UP_UP_UP(0, UP.y * 3),
    UP_UP_UP_UP(0, UP.y * 4),
    UP_UP_UP_UP_UP(0, UP.y * 5),
    UP_UP_UP_UP_UP_UP(0, UP.y * 6),
    UP_UP_UP_UP_UP_UP_UP(0, UP.y * 7),
    DOWN_DOWN(0, DOWN.y * 2),
    DOWN_DOWN_DOWN(0, DOWN.y * 3),
    DOWN_DOWN_DOWN_DOWN(0, DOWN.y * 4),
    DOWN_DOWN_DOWN_DOWN_DOWN(0, DOWN.y * 5),
    DOWN_DOWN_DOWN_DOWN_DOWN_DOWN(0, DOWN.y * 6),
    DOWN_DOWN_DOWN_DOWN_DOWN_DOWN_DOWN(0, DOWN.y * 7),
    LEFT_LEFT(LEFT.x * 2, 0),
    LEFT_LEFT_LEFT(LEFT.x * 3, 0),
    LEFT_LEFT_LEFT_LEFT(LEFT.x * 4, 0),
    LEFT_LEFT_LEFT_LEFT_LEFT(LEFT.x * 5, 0),
    LEFT_LEFT_LEFT_LEFT_LEFT_LEFT(LEFT.x * 6, 0),
    LEFT_LEFT_LEFT_LEFT_LEFT_LEFT_LEFT(LEFT.x * 7, 0),
    RIGHT_RIGHT(RIGHT.x * 2, 0),
    RIGHT_RIGHT_RIGHT(RIGHT.x * 3, 0),
    RIGHT_RIGHT_RIGHT_RIGHT(RIGHT.x * 4, 0),
    RIGHT_RIGHT_RIGHT_RIGHT_RIGHT(RIGHT.x * 5, 0),
    RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT(RIGHT.x * 6, 0),
    RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT(RIGHT.x * 7, 0),
    UP_UP_LEFT(LEFT.x, UP.y * 2),
    UP_UP_RIGHT(RIGHT.x, UP.y * 2),
    DOWN_DOWN_LEFT(LEFT.x, DOWN.y * 2),
    DOWN_DOWN_RIGHT(RIGHT.x, DOWN.y * 2),
    RIGHT_RIGHT_UP(RIGHT.x * 2, UP.y),
    RIGHT_RIGHT_DOWN(RIGHT.x * 2, DOWN.y),
    LEFT_LEFT_UP(LEFT.x * 2, UP.y),
    LEFT_LEFT_DOWN(LEFT.x * 2, DOWN.y),
    LEFT_UP_LEFT_UP(LEFT_UP.x * 2, LEFT_UP.y * 2),
    LEFT_UP_LEFT_UP_LEFT_UP(LEFT_UP.x * 3, LEFT_UP.y * 3),
    LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP(LEFT_UP.x * 4, LEFT_UP.y * 4),
    LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP(LEFT_UP.x * 5, LEFT_UP.y * 5),
    LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP(LEFT_UP.x * 6, LEFT_UP.y * 6),
    LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP(LEFT_UP.x * 7, LEFT_UP.y * 7),
    RIGHT_UP_RIGHT_UP(RIGHT_UP.x * 2, RIGHT_UP.y * 2),
    RIGHT_UP_RIGHT_UP_RIGHT_UP(RIGHT_UP.x * 3, RIGHT_UP.y * 3),
    RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP(RIGHT_UP.x * 4, RIGHT_UP.y * 4),
    RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP(RIGHT_UP.x * 5, RIGHT_UP.y * 5),
    RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP(RIGHT_UP.x * 6, RIGHT_UP.y * 6),
    RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP(RIGHT_UP.x * 7, RIGHT_UP.y * 7),
    LEFT_DOWN_LEFT_DOWN(LEFT_DOWN.x * 2, LEFT_DOWN.y * 2),
    LEFT_DOWN_LEFT_DOWN_LEFT_DOWN(LEFT_DOWN.x * 3, LEFT_DOWN.y * 3),
    LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN(LEFT_DOWN.x * 4, LEFT_DOWN.y * 4),
    LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN(LEFT_DOWN.x * 5, LEFT_DOWN.y * 5),
    LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN(LEFT_DOWN.x * 6, LEFT_DOWN.y * 6),
    LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN(LEFT_DOWN.x * 7, LEFT_DOWN.y * 7),
    RIGHT_DOWN_RIGHT_DOWN(RIGHT_DOWN.x * 2, RIGHT_DOWN.y * 2),
    RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN(RIGHT_DOWN.x * 3, RIGHT_DOWN.y * 3),
    RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN(RIGHT_DOWN.x * 4, RIGHT_DOWN.y * 4),
    RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN(RIGHT_DOWN.x * 5, RIGHT_DOWN.y * 5),
    RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN(RIGHT_DOWN.x * 6, RIGHT_DOWN.y * 6),
    RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN(RIGHT_DOWN.x * 7, RIGHT_DOWN.y * 7),
    ;
    //@formatter:on

    private final int x;
    private final int y;

    Movement(
        final int x,
        final int y
    ) {
        this.x = x;
        this.y = y;
    }

    public int x() {
        return x;
    }

    public int y() {
        return y;
    }
}
