package chess;

import java.util.List;
import java.util.Map;

public enum PieceType {
    PAWN("폰", Map.of(
        Color.BLACK,
        List.of(
            new Position(Row.SEVEN, Column.A),
            new Position(Row.SEVEN, Column.B),
            new Position(Row.SEVEN, Column.C),
            new Position(Row.SEVEN, Column.D),
            new Position(Row.SEVEN, Column.E),
            new Position(Row.SEVEN, Column.F),
            new Position(Row.SEVEN, Column.G),
            new Position(Row.SEVEN, Column.H))
        , Color.WHITE,
        List.of(
            new Position(Row.TWO, Column.A),
            new Position(Row.TWO, Column.B),
            new Position(Row.TWO, Column.C),
            new Position(Row.TWO, Column.D),
            new Position(Row.TWO, Column.E),
            new Position(Row.TWO, Column.F),
            new Position(Row.TWO, Column.G),
            new Position(Row.TWO, Column.H))),
        Map.of(
            Color.BLACK,
            List.of(
                Movement.DOWN),
            Color.WHITE,
            List.of(
                Movement.UP))),
    ROOK("룩", Map.of(
        Color.BLACK,
        List.of(
            new Position(Row.EIGHT, Column.A),
            new Position(Row.EIGHT, Column.H)),
        Color.WHITE,
        List.of(
            new Position(Row.ONE, Column.A),
            new Position(Row.ONE, Column.H))),
        Map.of(
            Color.BLACK,
            List.of(
                Movement.UP,
                Movement.UP_UP,
                Movement.UP_UP_UP,
                Movement.UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP_UP,
                Movement.DOWN,
                Movement.DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.LEFT,
                Movement.LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.RIGHT,
                Movement.RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT),
            Color.WHITE,
            List.of(
                Movement.UP,
                Movement.UP_UP,
                Movement.UP_UP_UP,
                Movement.UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP_UP,
                Movement.DOWN,
                Movement.DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.LEFT,
                Movement.LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.RIGHT,
                Movement.RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT))),
    KNIGHT("나이트", Map.of(
        Color.BLACK, List.of(
            new Position(Row.EIGHT, Column.B),
            new Position(Row.EIGHT, Column.G)),
        Color.WHITE, List.of(
            new Position(Row.ONE, Column.B),
            new Position(Row.ONE, Column.G))),
        Map.of(
            Color.BLACK, List.of(
                Movement.UP_UP_LEFT,
                Movement.UP_UP_RIGHT,
                Movement.DOWN_DOWN_LEFT,
                Movement.DOWN_DOWN_RIGHT,
                Movement.LEFT_LEFT_UP,
                Movement.LEFT_LEFT_DOWN,
                Movement.RIGHT_RIGHT_UP,
                Movement.RIGHT_RIGHT_DOWN),
            Color.WHITE, List.of(
                Movement.UP_UP_LEFT,
                Movement.UP_UP_RIGHT,
                Movement.DOWN_DOWN_LEFT,
                Movement.DOWN_DOWN_RIGHT,
                Movement.LEFT_LEFT_UP,
                Movement.LEFT_LEFT_DOWN,
                Movement.RIGHT_RIGHT_UP,
                Movement.RIGHT_RIGHT_DOWN))),
    BISHOP("비숍", Map.of(
        Color.BLACK, List.of(
            new Position(Row.EIGHT, Column.C),
            new Position(Row.EIGHT, Column.F)),
        Color.WHITE, List.of(
            new Position(Row.ONE, Column.C),
            new Position(Row.ONE, Column.F))),
        Map.of(
            Color.BLACK, List.of(
                Movement.LEFT_UP,
                Movement.LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN),
            Color.WHITE, List.of(
                Movement.LEFT_UP,
                Movement.LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN))),
    QUEEN("퀸", Map.of(
        Color.BLACK, List.of(
            new Position(Row.EIGHT, Column.E)),
        Color.WHITE, List.of(
            new Position(Row.ONE, Column.E))),
        Map.of(
            Color.BLACK, List.of(
                Movement.UP,
                Movement.UP_UP,
                Movement.UP_UP_UP,
                Movement.UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP_UP,
                Movement.DOWN,
                Movement.DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.LEFT,
                Movement.LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.RIGHT,
                Movement.RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.LEFT_UP,
                Movement.LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN),
            Color.WHITE, List.of(
                Movement.UP,
                Movement.UP_UP,
                Movement.UP_UP_UP,
                Movement.UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP,
                Movement.UP_UP_UP_UP_UP_UP_UP,
                Movement.DOWN,
                Movement.DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.DOWN_DOWN_DOWN_DOWN_DOWN_DOWN_DOWN,
                Movement.LEFT,
                Movement.LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.LEFT_LEFT_LEFT_LEFT_LEFT_LEFT_LEFT,
                Movement.RIGHT,
                Movement.RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT_RIGHT,
                Movement.LEFT_UP,
                Movement.LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP_LEFT_UP,
                Movement.RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP_RIGHT_UP,
                Movement.LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN_LEFT_DOWN,
                Movement.RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN,
                Movement.RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN_RIGHT_DOWN))),
    KING("킹", Map.of(
        Color.BLACK, List.of(
            new Position(Row.EIGHT, Column.D))
        , Color.WHITE, List.of(
            new Position(Row.ONE, Column.D))),
        Map.of(
            Color.BLACK, List.of(
                Movement.UP,
                Movement.DOWN,
                Movement.LEFT,
                Movement.RIGHT,
                Movement.LEFT_UP,
                Movement.RIGHT_UP,
                Movement.LEFT_DOWN,
                Movement.RIGHT_DOWN),
            Color.WHITE, List.of(
                Movement.UP,
                Movement.DOWN,
                Movement.LEFT,
                Movement.RIGHT,
                Movement.LEFT_UP,
                Movement.RIGHT_UP,
                Movement.LEFT_DOWN,
                Movement.RIGHT_DOWN)));

    private final String symbol;
    private final Map<Color, List<Position>> initialPositions;
    private final Map<Color, List<Movement>> movements;

    PieceType(
        final String symbol,
        final Map<Color, List<Position>> initialPositions,
        final Map<Color, List<Movement>> movements
    ) {
        this.symbol = symbol;
        this.initialPositions = initialPositions;
        this.movements = movements;
    }

    public String getSymbol() {
        return symbol;
    }

    public Map<Color, List<Position>> getInitialPositions() {
        return initialPositions;
    }

    public List<Movement> getMovements(final Color color) {
        return movements.get(color);
    }
}
