--create table game (
--    game_id int primary key auto_increment,
--    name varchar(20) not null unique ,
--    state varchar(20) not null
--);
--
--create table piece (
--    piece_id int primary key auto_increment,
--    name varchar(20) not null,
--    position varchar(2) not null,
--    game_id int not null,
--    foreign key (game_id) references game (game_id) on delete cascade
--);