CREATE TABLE move (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_column TINYINT NOT NULL,
    source_row TINYINT NOT NULL,
    target_column TINYINT NOT NULL,
    target_row TINYINT NOT NULL,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);
