CREATE TABLE user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);

CREATE TABLE game (
    id BIGINT NOT NULL AUTO_INCREMENT,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);

CREATE TABLE user_game (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);
ALTER TABLE user_game ADD FOREIGN KEY (user_id) REFERENCES user (`id`) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE user_game ADD FOREIGN KEY (game_id) REFERENCES game (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE move (
    id BIGINT NOT NULL AUTO_INCREMENT,
    game_id BIGINT NOT NULL,
    source_column TINYINT NOT NULL,
    source_row TINYINT NOT NULL,
    target_column TINYINT NOT NULL,
    target_row TINYINT NOT NULL,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);
ALTER TABLE move ADD FOREIGN KEY (game_id) REFERENCES game(`id`) ON UPDATE CASCADE ON DELETE CASCADE;
