package chess.constant;

public enum ExceptionCode {
    INVALID_COMMAND_PARAMETER,
    UNDEFINED_COMMAND_TYPE,
    PIECE_CAN_NOT_FOUND,
    PIECE_MOVING_PATH_BLOCKED,
    ACCESS_BLANK_PIECE,
    INVALID_DESTINATION,
    TARGET_IS_SAME_COLOR,
    GAME_END,
    GAME_NOT_INITIALIZED,
    INVALID_COMMAND,
    GAME_ALREADY_RUNNING,
    INVALID_TURN,
    GAME_OVER_STATE;
}
