package chess;

import chess.domain.Column;
import chess.domain.Position;
import chess.domain.Row;

public class PositionCache {
    public static final Position POSITION_0_0 = Position.of(Row.ROW_A, Column.COLUMN_8);
    public static final Position POSITION_0_1 = Position.of(Row.ROW_A, Column.COLUMN_7);
    public static final Position POSITION_0_2 = Position.of(Row.ROW_A, Column.COLUMN_6);
    public static final Position POSITION_0_3 = Position.of(Row.ROW_A, Column.COLUMN_5);
    public static final Position POSITION_0_4 = Position.of(Row.ROW_A, Column.COLUMN_4);
    public static final Position POSITION_0_5 = Position.of(Row.ROW_A, Column.COLUMN_3);
    public static final Position POSITION_0_6 = Position.of(Row.ROW_A, Column.COLUMN_2);
    public static final Position POSITION_0_7 = Position.of(Row.ROW_A, Column.COLUMN_1);
    public static final Position POSITION_1_0 = Position.of(Row.ROW_B, Column.COLUMN_8);
    public static final Position POSITION_1_1 = Position.of(Row.ROW_B, Column.COLUMN_7);
    public static final Position POSITION_1_2 = Position.of(Row.ROW_B, Column.COLUMN_6);
    public static final Position POSITION_1_3 = Position.of(Row.ROW_B, Column.COLUMN_5);
    public static final Position POSITION_1_4 = Position.of(Row.ROW_B, Column.COLUMN_4);
    public static final Position POSITION_1_5 = Position.of(Row.ROW_B, Column.COLUMN_3);
    public static final Position POSITION_1_6 = Position.of(Row.ROW_B, Column.COLUMN_2);
    public static final Position POSITION_1_7 = Position.of(Row.ROW_B, Column.COLUMN_1);
    public static final Position POSITION_2_0 = Position.of(Row.ROW_C, Column.COLUMN_8);
    public static final Position POSITION_2_1 = Position.of(Row.ROW_C, Column.COLUMN_7);
    public static final Position POSITION_2_2 = Position.of(Row.ROW_C, Column.COLUMN_6);
    public static final Position POSITION_2_3 = Position.of(Row.ROW_C, Column.COLUMN_5);
    public static final Position POSITION_2_4 = Position.of(Row.ROW_C, Column.COLUMN_4);
    public static final Position POSITION_2_5 = Position.of(Row.ROW_C, Column.COLUMN_3);
    public static final Position POSITION_2_6 = Position.of(Row.ROW_C, Column.COLUMN_2);
    public static final Position POSITION_2_7 = Position.of(Row.ROW_C, Column.COLUMN_1);
    public static final Position POSITION_3_0 = Position.of(Row.ROW_D, Column.COLUMN_8);
    public static final Position POSITION_3_1 = Position.of(Row.ROW_D, Column.COLUMN_7);
    public static final Position POSITION_3_2 = Position.of(Row.ROW_D, Column.COLUMN_6);
    public static final Position POSITION_3_3 = Position.of(Row.ROW_D, Column.COLUMN_5);
    public static final Position POSITION_3_4 = Position.of(Row.ROW_D, Column.COLUMN_4);
    public static final Position POSITION_3_5 = Position.of(Row.ROW_D, Column.COLUMN_3);
    public static final Position POSITION_3_6 = Position.of(Row.ROW_D, Column.COLUMN_2);
    public static final Position POSITION_3_7 = Position.of(Row.ROW_D, Column.COLUMN_1);
    public static final Position POSITION_4_0 = Position.of(Row.ROW_E, Column.COLUMN_8);
    public static final Position POSITION_4_1 = Position.of(Row.ROW_E, Column.COLUMN_7);
    public static final Position POSITION_4_2 = Position.of(Row.ROW_E, Column.COLUMN_6);
    public static final Position POSITION_4_3 = Position.of(Row.ROW_E, Column.COLUMN_5);
    public static final Position POSITION_4_4 = Position.of(Row.ROW_E, Column.COLUMN_4);
    public static final Position POSITION_4_5 = Position.of(Row.ROW_E, Column.COLUMN_3);
    public static final Position POSITION_4_6 = Position.of(Row.ROW_E, Column.COLUMN_2);
    public static final Position POSITION_4_7 = Position.of(Row.ROW_E, Column.COLUMN_1);
    public static final Position POSITION_5_0 = Position.of(Row.ROW_F, Column.COLUMN_8);
    public static final Position POSITION_5_1 = Position.of(Row.ROW_F, Column.COLUMN_7);
    public static final Position POSITION_5_2 = Position.of(Row.ROW_F, Column.COLUMN_6);
    public static final Position POSITION_5_3 = Position.of(Row.ROW_F, Column.COLUMN_5);
    public static final Position POSITION_5_4 = Position.of(Row.ROW_F, Column.COLUMN_4);
    public static final Position POSITION_5_5 = Position.of(Row.ROW_F, Column.COLUMN_3);
    public static final Position POSITION_5_6 = Position.of(Row.ROW_F, Column.COLUMN_2);
    public static final Position POSITION_5_7 = Position.of(Row.ROW_F, Column.COLUMN_1);
    public static final Position POSITION_6_0 = Position.of(Row.ROW_G, Column.COLUMN_8);
    public static final Position POSITION_6_1 = Position.of(Row.ROW_G, Column.COLUMN_7);
    public static final Position POSITION_6_2 = Position.of(Row.ROW_G, Column.COLUMN_6);
    public static final Position POSITION_6_3 = Position.of(Row.ROW_G, Column.COLUMN_5);
    public static final Position POSITION_6_4 = Position.of(Row.ROW_G, Column.COLUMN_4);
    public static final Position POSITION_6_5 = Position.of(Row.ROW_G, Column.COLUMN_3);
    public static final Position POSITION_6_6 = Position.of(Row.ROW_G, Column.COLUMN_2);
    public static final Position POSITION_6_7 = Position.of(Row.ROW_G, Column.COLUMN_1);
    public static final Position POSITION_7_0 = Position.of(Row.ROW_H, Column.COLUMN_8);
    public static final Position POSITION_7_1 = Position.of(Row.ROW_H, Column.COLUMN_7);
    public static final Position POSITION_7_2 = Position.of(Row.ROW_H, Column.COLUMN_6);
    public static final Position POSITION_7_3 = Position.of(Row.ROW_H, Column.COLUMN_5);
    public static final Position POSITION_7_4 = Position.of(Row.ROW_H, Column.COLUMN_4);
    public static final Position POSITION_7_5 = Position.of(Row.ROW_H, Column.COLUMN_3);
    public static final Position POSITION_7_6 = Position.of(Row.ROW_H, Column.COLUMN_2);
    public static final Position POSITION_7_7 = Position.of(Row.ROW_H, Column.COLUMN_1);
}
